# Generated by Django 2.1 on 2019-04-22 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20190310_1233'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='followed_thread',
            field=models.ManyToManyField(blank=True, related_name='followers', to='threads.Thread'),
        ),
        migrations.AddField(
            model_name='user',
            name='followed_user',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
