# Generated by Django 2.1 on 2019-04-24 13:42

import app.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190422_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'this nick was taken.'}, help_text='required. 42 characters or fewer. letters, digits and ./+/-/_ only.', max_length=42, unique=True, validators=[app.users.models.UsernameValidator()], verbose_name='username'),
        ),
    ]
