# Generated by Django 2.1 on 2019-03-09 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=35, unique=True)),
                ('descr', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=49, unique=True)),
                ('lang', models.CharField(max_length=5)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_entry', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_entry'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='thread',
            field=models.ManyToManyField(blank=True, related_name='tags', to='threads.Thread'),
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together={('title', 'lang')},
        ),
    ]
