# Generated by Django 2.1 on 2018-08-24 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='thread',
            field=models.ManyToManyField(related_name='tags', related_query_name='', to='threads.Thread'),
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together={('title', 'lang')},
        ),
    ]
