# Generated by Django 2.2.2 on 2019-06-30 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['last_entry'], name='threads_thr_last_en_95f09d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together={('title', 'lang')},
        ),
    ]
