# Generated by Django 2.1 on 2018-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20180824_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='thread',
            field=models.ManyToManyField(null=True, related_name='tags', to='threads.Thread'),
        ),
    ]
