# Generated by Django 2.2.2 on 2019-06-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20190619_1141'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['last_entry'], name='threads_thr_last_en_95f09d_idx'),
        ),
    ]
