# Generated by Django 2.1 on 2018-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20180826_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='thread',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='threads.Thread'),
        ),
    ]
