# Generated by Django 2.1 on 2019-01-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20180826_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
