# Generated by Django 2.1 on 2019-03-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_auto_20190112_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
