# Generated by Django 2.2.2 on 2019-06-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20190619_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
