# Generated by Django 2.1 on 2019-03-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20180824_1328'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='entry',
            order_with_respect_to='thread',
        ),
    ]
