# Generated by Django 2.1 on 2019-03-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20190302_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='entry',
            order_with_respect_to=None,
        ),
    ]
