# Generated by Django 2.2.2 on 2019-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20190621_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
