# Generated by Django 2.2.2 on 2019-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['created_at'], name='entries_ent_created_823464_idx'),
        ),
    ]
