# Generated by Django 2.2.2 on 2019-06-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('message_type', models.CharField(choices=[('ADV', 'advice'), ('COM', 'complain'), ('OTH', 'other')], max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lang', models.CharField(choices=[('en', 'English'), ('tr', 'Turkish')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
