# Generated by Django 2.2.2 on 2019-06-21 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_type',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
